use-escaping: true
template-arb-file: nomna_vi.arb
arb-dir: assets
output-dir: lib\src
output-class: NomnaLocale
output-localization-file: nomna_locale.dart
untranslated-messages-file: .dart_tool\untranslated_locale.json