use-escaping: true
synthetic-package: false
template-arb-file: nomna_vi.arb
arb-dir: lib\input
output-dir: lib\output
output-class: NomnaLocalizations
output-localization-file: nomna_localizations.dart
untranslated-messages-file: .dart_tool\untranslated_localizations.json